### ISSUE TITLE
question: Inconsistent naming

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-csharp-sdk#5]
There are  `DeleteRoutes` and `DeleteAvoidanceZone` methods.

But for other entities appropriate methods are called `RemoveXXX`

May be is it worth to rename?

**Comment by Olman62** [comment]
These two wards are almost synonyms, by while delete means erasing
something, remove means to take something from its place (list, position
etc) - so, I think, delete is more preferable. In other hand, I think using
both words even preferable, because user will know that for us they are
synonyms.

But this is my own opinion - this happened because on this project worked
many programmers and each of them has own style.
